id: P2AE80B8E
initial_creation_type: input
source_metadata:
  title: Tsok Series
  language: fr
  description: 'Lotsawa House presents the following texts related to the practice
    of tsok (tshogs) or feast-gathering (Skt. gaṇacakra):'
  volume:
    d27c3ddc6d404b18a9a3df9c5c8ac54a:
      title: Introduction to Gaṇacakra (Tsok)
      parent: Introduction
    82d798a3440748d3a0b9a6d3185d87a2:
      title: A Concise Explanation of Gaṇacakra
      parent: Explanation
    d07938f904d04917b8ed6cc3debee0e4:
      title: 'A Bouquet of Uḍumbara Flowers: An Explanation of the Tenth Day'
      parent: Explanation
    5ce12f200ad8429ba776af67b54854ca:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Explanation
    040a16abc69c452db7941f867df221e8:
      title: The Gaṇacakra Ritual
      parent: Explanation
    f40d3e2beb9a43eca4d97bedc1134593:
      title: 'Sweet Droplets of the Honey of Accomplishment: A Concise Explanation
        of the Indispensable Points of the Feast-Gathering'
      parent: Explanation
    0fa1abb5d2864aebbf79782f817c18e1:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Offering Liturgies
    5e429994791548709b8cf61ab4509929:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Offering Liturgies
    69622d0f88804211b671f407b09e887a:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Prayers
    20c90f3b487646f6ad2b62b725a8a1f1:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Prayers
    87d9325fdd7b4e63a40af26377f04b4d:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Prayers
    1b632a124cbf4d54867eeae9bff15df1:
      title: Brief Prayer of the Feast Gathering
      parent: Prayers
    7753cc4fc28949139d14a50bf8c16fc9:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Prayers
    147bff7790644bc3b865b09b424652a9:
      title: Food Offering Prayer
      parent: Prayers
    e430266db3934aa889aabdee5b9abf4f:
      title: Concise Tsok Feast
      parent: Prayers
    0f0bd9fe7cbd464fa5ffd8d3fcfe6dfc:
      title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the
        Vajra Seven-Line Prayer'
      parent: Prayers
    33fb80a156714068bad07ba0d85d0c7a:
      title: A Concise Feast Prayer
      parent: Prayers
    6298560604374d8f8e7f2c94a0ee72bb:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Remainder Offering
    081d7c5ad78c4a59a5ad0696de3defd4:
      title: The Song of the Vajra
      parent: Songs
    053ed5b1efa34a198ea12d3765ee940c:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Songs
    763eca8ec2904b109f007faf5eac3eec:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Songs
    42a00dc04bb74986bccf468f47c4ef73:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Songs
    6c187e5945964ed28c6c354b9bd6589c:
      title: Song of the Feast (Tsok Lu)
      parent: Songs
created_at: '2022-03-01T06:26:39.648073'
last_modified_at: '2022-03-01T06:26:39.648077'
